### ISSUE TITLE
Names (for classes, functions, variables etc) in Python can't start with a number

### ISSUE THREAD

**Issue by yawor** [mcanet/STL-Volume-Model-Calculator#18]
I've found in some recent change, that there's a class named `3DPrintingMaterials`, which is an invalid Python name, as names can't start with a number:
https://github.com/mcanet/STL-Volume-Model-Calculator/blob/ad57b78cfa25874adf570408bf5c8204f1f31d2b/volume_calculator.py#L14

**Comment by mcanet** [comment]
Yes, I fixed.
