### ISSUE TITLE
Negative volume

### ISSUE THREAD

**Issue by shravan2x** [mcanet/STL-Volume-Model-Calculator#6]
For some objects, I get negative volumes. Is this expected?

```
Choose desired print material of STL file below:
1 = ABS or 2 = PLA or 3 = 3k CFRP or 4 = Plexiglass : 1
Desktop/gt2_20tooth.stl
total triangles: 1919252000
End calculate triangles volume
Total mass: -6.827174352201647e+92 g
Total volume: -6.564590723270814e+92 cm^3
```

**Comment by DJGummikuh** [comment]
I have the same issue, with the added twist that it says "Total mass could not be calculated"

**Comment by mcanet** [comment]
I push a fix for that issue. It is looking if mass is negative response that cannot be calculated.
